# Generated by Django 6.0.3 on 2026-03-05 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_alerts',
            field=models.BooleanField(default=False),
        ),
    ]
