# Generated by Django 6.0.3 on 2026-03-05 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0002_alter_accessibility_name_alter_contextwindow_name_and_more'),
        ('user', '0002_customuser_email_alerts'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='favourite_tools',
            field=models.ManyToManyField(blank=True, to='tool.tool'),
        ),
    ]
