# Generated by Django 6.0.3 on 2026-03-04 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accessibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ContextWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_name', models.CharField(max_length=255)),
                ('release_year', models.IntegerField()),
                ('intelligence_type', models.CharField(max_length=255)),
                ('key_functionality', models.TextField()),
                ('pricing_model', models.CharField(max_length=255)),
                ('api_availability', models.CharField(max_length=255)),
                ('popularity_votes', models.IntegerField(default=0)),
                ('website_url', models.URLField()),
                ('accessibility', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tool.accessibility')),
                ('context_window', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tool.contextwindow')),
                ('developer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tool.developer')),
                ('primary_domain', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tool.domain')),
            ],
        ),
    ]
