# Generated by Django 6.0.3 on 2026-03-06 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0003_tool_embedding_recommendationresults'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendationresults',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
