# Generated by Django 6.0.3 on 2026-03-06 22:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0004_recommendationresults_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendationresults',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
