# Generated by Django 6.0.3 on 2026-03-07 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0005_recommendationresults_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendationresults',
            name='error',
            field=models.TextField(blank=True, null=True),
        ),
    ]
